### ISSUE TITLE
Failed to query view by SG(1.1.0) admin rest api

### ISSUE THREAD

**Issue by atom992** [couchbase/sync_gateway#1135]
Hi, I can not query the view by SG Admin API,(SG 1.1.0 + couchabse 3.1.0)
I followed:
http://developer.couchbase.com/documentation/mobile/1.1.0/develop/guides/sync-gateway/accessing-cb-views/creating-and-using-a-view/index.html
and when I add the view :
{
"views":{
"all_lists":{
"map":"function (doc, meta) { if (doc._sync === undefined || meta.id.substring(0,6) == \"_sync:\") { return; } if (doc.type != \"list\") { return; } emit(doc.title, doc.owner); }"
}
}
}
I can check the view by CB web UI,and the view looks like this:
function(doc,meta) {
                    var sync = doc._sync;

```
                if (sync === undefined || meta.id.substring(0,6) == "_sync:")

                  return;

                if ((sync.flags & 1) || sync.deleted)

                  return;

                delete doc._sync;

                meta.rev = sync.rev;

                (function (doc, meta) { if (doc._sync === undefined || meta.id.substring(0,6) == "_sync:") { return; } if (doc.type != "list") { return; } emit(doc.title, doc.owner); }) (doc, meta); }
```

SG add some logic into it.
but when I add some test data by:
curl -X PUT -H "Content-type: application/json" localhost:4985/db/lists:001 -d '{"type":"list","title":"title_test","owner":"owner_test"}'
I can not query this data by SG admin REST API (and CB web UI) .

when I remove "delete doc._sync; " in map function, and query view by add full_set=true parameter,I can get the data.
I don't know what useful about "delete doc._sync;" and "meta.rev = sync.rev;"
but I still can not query my custom view by SG admin rest api.
btw, I can query the view by CB admin UI.

**Comment by atom992** [comment]
I check the code ,and wrap the views by:
https://github.com/couchbase/sync_gateway/blob/4d995d2d00d4d703d4da41c8ccf525d99ce37d7f/src/github.com/couchbase/sync_gateway/db/design_doc.go#L64
but still can not query data from SG admin rest api or SG rest api.(but can query data with channel array with CB admin UI)

**Comment by ajres** [comment]
An issue with multiple custom views in one design document was just fixed see: #1109, this was related to the delete doc._sync line you referenced above.

It would be worth you building SG from master and retesting your view.

**Comment by atom992** [comment]
ok, I will try.

**Comment by atom992** [comment]
I build from src, using 
Couchbase Sync Gateway/master(226819e) 
with couchbase Version: 3.1.0-1776 Enterprise Edition (build-1776)
It still not working.

**Comment by ajres** [comment]
Looking back through the ticket, the doc._sync property is removed before the doc is passed to your map function, so I think your function will always return without calling emit().

try the following modified view definition:

```
{
    "views":{
        "all_lists":{
            "map":"function (doc, meta) {if (doc.type != \"list\") { return; } emit(doc.title, doc.owner); } "
        }
    }
}
```

**Comment by atom992** [comment]
without "if (doc._sync === undefined || meta.id.substring(0,6) == "_sync:") { return; }" , the query still not work.

**Comment by adamcfraser** [comment]
I think the issue is that you're including the "if (sync === undefined || meta.id.substring(0,6) == "_sync:")" in the view you are creating.  I would think that your view should just be:

if (doc.type != "list") { return; } emit(doc.title, doc.owner);

as Sync Gateway is already wrapping the function appropriately with the sync check.   Since the Sync Gateway wrapper is stripping out the_sync metadata, your sync check is always going to fail.

**Comment by ajres** [comment]
These are the steps I followed to try and reproduce your issue, but it worked as expected for me, this is using Couchbase Server 3.0.1 and Sync Gateway built from master, 

If you follow the steps below, at what point do your results diverge from the expected results?

Sync Gateway config

```
{
    "log": ["*"],
    "databases": {
         "db": {
                "server": "http://localhost:8091",
                "bucket":"bucket-1",
                "users": {
                    "GUEST": {"disabled": false, "admin_channels": ["*"]}
                }
          }
     }
}
```

View definition in file textview.json

```
{
  "views": {
    "all_lists":{
      "map":"function (doc, meta) {if (doc.type != \"list\") { return; } emit(doc.title, doc.owner); }"
    }
  }
}
```

Add views to 'db'

```
curl -vX PUT localhost:4985/db/_design/myviews -H "Content-Type: application/json" -d @testview.json
```

Add test file to 'db'

```
curl -vX PUT http://localhost:4985/db/doc2 -H "Content-Type: application/json" -d '{"type":"list","title":"title_test","owner":"owner_test"}'
```

Query view

```
curl -X GET http://localhost:4985/db/_design/myviews/_view/all_lists?stale=false
```

Query results

```
{"total_rows":1,"rows":[{"id":"doc2","key":"title_test","value":"owner_test"}],"Collator":{}}
```

**Comment by atom992** [comment]
yes, the all_lists view also return data. My custom view can not return data.

**Comment by ajres** [comment]
When you say 'custom view' is this added via the views json file, in which case can you post the custom view code and I can test it here.
Or is this a view you have manually modified via the Couchbase Server Admin UI, in which case what is it you want to achieve that can not be achieved via the views json document?

**Comment by atom992** [comment]
I add the view by views json file, and It include more than one view, it is the same view json file as I added into couchbase by:
curl -X PUT -H 'Content-Type: application/json' http://127.0.0.1:8092/cbdb/_design/dev_view -d @./init_view.ddoc

**Comment by atom992** [comment]
My view like this:

{
    "views"
:
    {
        "getDocByLoginName"
    :
        {
            "map"
        :
            "function (doc,meta) {\n\n\n    if(doc.type ==\"GST\" && doc.phone_number){\n        var login_name = meta.id.split(\":\")[2]; \n        emit(doc.phone_number,login_name); \n        emit(login_name,login_name);\n    }\n }"
        },
        "getDocByID"
    :
        {
            "map"
        :
            "function (doc,meta) {\n                         emit(meta.id,doc);\n                    }"
        }
    }
}

the sample data is like:
curl -X PUT -H "Content-type: application/json" localhost:4985/sgdb/GST:USR:user01 -d '{"type":"GST","phone_number":"12345678"}'

**Comment by ajres** [comment]
I followed the same steps I posted above but with your custom views and your document.

When I query the views I get:

```
curl -X GET http://localhost:4985/db/_design/myviews/_view/getDocByLoginName?stale=false
{"total_rows":2,"rows":[{"id":"GST:USR:user01","key":"12345678","value":"user01"},{"id":"GST:USR:user01","key":"user01","value":"user01"}],"Collator":{}}
```

and

```
curl -X GET http://localhost:4985/db/_design/myviews/_view/getDocByID?stale=false
{"total_rows":1,"rows":[{"id":"GST:USR:user01","key":"GST:USR:user01","value":{"phone_number":"12345678","type":"GST"}}],"Collator":{}}
```

Are you using the ?stale=false option when querying? If not the view will not be re-indexed before returning the results and recent doc updates may be missing.

**Comment by atom992** [comment]
yes, I I include stale=false when querying. My query like this:
curl http://127.0.0.1:4985/sgdb/_design/dev_view/_view/getDocByLoginName?full_set=true&inclusive_end=true&key=%22user01%22&stale=false&connection_timeout=60000&limit=10&skip=0
but have no values. but If I remove the key, I can get some data.

**Comment by atom992** [comment]
btw, I have 300+ matched record but the total_rows show 16 only.

**Comment by ajres** [comment]
Are you able to upload your test data to a gist and provide the specific query and results that you get. 

Then we can try and create a reproducible unit test.

**Comment by atom992** [comment]
I have a complexity sync function and some complexity data that is privately. and the sample view just  put here. following is my test data Generate shell Scripts :

#!/bin/bash
TOTLE=100
USER=(usera userb userc userd)
for u in ${USER[@]}
  do
    for i in `seq 1 $TOTLE`;
        do
                USR=$u$i
                DATA=\'{\"name\":\"$USR\"\,\"password\":\"123456\"}\'
                CMD="curl -X PUT localhost:4985/sgdb/_user/$USR -d "$DATA
                echo $CMD >> ./init_user.sh
        done

```
for i in `seq 1 $TOTLE`;
    do
            USR=$u$i
            let "PHONE_NUMBER=12345000000+$i"
            DATA=\'{\"type\"\:\"GST\"\,\"phone_number\"\:\"$PHONE_NUMBER\"}\'
            CMD="curl -X PUT -H \"Content-Type:application/json\" $USR:123456@localhost:4984/sgdb/GST:USR:$USR -d "$DATA
            echo $CMD >> ./init_user.sh
    done
```

  done

**Comment by adamcfraser** [comment]
Closing based on age and lack of clear repro scenario.  Can reopen in JIRA if this is still an issue.
