### ISSUE TITLE
sync-gateway builds are failing test with GO 1.5.2

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/sync_gateway#1378]

**Comment by adamcfraser** [comment]
Unit tests that were failing the build have been fixed with #1380 - latest unix-builds on master are green for centos and macosx.

**Comment by michaelkwok** [comment]
Actually I still see 2 failed targets, ubuntu and macosx, for community editions.  All other targets are green.
