### ISSUE TITLE
Windows Installshield installer error: missing file for action remove wrapper

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#1564]
![image](https://cloud.githubusercontent.com/assets/759830/12835272/85887a84-cb63-11e5-882b-de4b6452d641.png)

**Comment by michaelkwok** [comment]
@ajres The .ism file doesn't look correct.

Here is what I found in the sync_gateway.ism.
        <row><td>PATH_TO_EXAMPLES_FILES</td><td>C:\Users\andy\Documents\installer-build\app-under-test\sync_gateway\examples</td><td/><td>2</td></row>
        <row><td>PATH_TO_JENKINS_WORKSPACE</td><td>C:\jenkins\workspace\build_sync_gateway_master_win-2008-x86</td><td/><td>2</td></row>
        <row><td>PATH_TO_LICENSE_FILE</td><td>&lt;PATH_TO_SYNC_GATEWAY_FILES&gt;</td><td/><td>2</td></row>
        <row><td>PATH_TO_SG-WINDOWS_FILES</td><td>&lt;PATH_TO_SYNC_GATEWAY_FILES&gt;\service\sg-windows</td><td/><td>2</td></row>
        <row><td>PATH_TO_SYNC_GATEWAY_FILES</td><td>&lt;PATH_TO_JENKINS_WORKSPACE&gt;\app-under-test\sync_gateway\build\opt\couchbase-sync-gateway</td>

I am guessing you might have pushed the wrong file.  Those directories need to use relative paths.

**Comment by michaelkwok** [comment]
Actually, I meant to say sync-gateway.ism.

**Comment by michaelkwok** [comment]
I see the same thing in sg-accel.ism.  There is a good chance you pushed the wrong set of .ism files.   In sg-accel.ism, I don't see where PATH_TO_SG_ECCEL is set for "PATH_TO_SG_ECCEL_FILES&gt;\examples\basic_sg_accel_config.json"

Can you also update the product name to SG_Accel before you check-in?
        <row><td>ProductName</td><td>SG_Eccel</td><td/></row>

**Comment by ajres** [comment]
I just pushed an updated sync-gateway.ism to master, this makes PATH_TO_EXAMPLES_FILES relative, but I left PATH_TO_JENKINS_WORKSPACE as absolute as this has not changed for a long time and looks to get overridden when running ISCmdBld.exe.

**Comment by ajres** [comment]
I have pushed an updated sg-accel.ism to master, this makes path variables relative with the exception of PATH_TO_JENKINS_WORKSPACE, same as above.
Also fixed the Product name typo.

**Comment by rainerg2000** [comment]
Verification of this issue with "http://www.couchbase.com/dl/releases/couchbase-sync-gateway/1.2.0/couchbase-sync-gateway-enterprise_1.2.0-83_x86_64.exe" failed.
The originally reported error still occurs. See attached screenshot from my test server.
![syncgateway issue](https://cloud.githubusercontent.com/assets/2896215/12893213/beb924d2-ce44-11e5-9051-5c05f5094e7f.PNG)

**Comment by ajres** [comment]
Opened #1573 to track this new issue, @rainerg2000 please post to the new ticket.

**Comment by zgramana** [comment]
A workaround is also available on issue #1573.
