### ISSUE TITLE
XATTRs - Error unmarshalling doc

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2489]
### Sync Gateway version
1.4.2(332;52a0e3d)

### Operating system
CentOS 7

### Log output
https://gist.github.com/sethrosetter/65bbbd08f48eeb8bb3ce378774e2008b#file-gistfile1-txt-L418-L512

### Expected behavior
Changes not returning

### Actual behavior
Changes should be sent

### Steps to reproduce
1.  `pytest --skip-provisioning --pdb --xattrs -s --mode=cc --server-version=5.0.0-2492 --sync-gateway-version=1.4.2-332 -k "test_backfill_channels_oneshot_changes[custom_sync/access-CHANNEL-REST]" testsuites/syncgateway/functional/tests` 
2. Or you can run http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc with test_backfill_channels_oneshot_changes[custom_sync/access-CHANNEL-REST].

**Comment by adamcfraser** [comment]
Looks like there's a problem with the views not returning xattrs in recent Spock builds.  Working with the views team to resolve.

**Comment by adamcfraser** [comment]
View related issues should be addressed by https://github.com/couchbase/sync_gateway/pull/2494

**Comment by sethrosetter** [comment]
I'm still seeing the unmarshalling errors with `1.4.2-337` with the same test

```
2017-04-25T00:49:15.524Z CRUD: Stored doc "8d4da5c1-f546-4a7b-93dc-f5cb1ede1121" / "1-e66d6718ae9b3234d849b1cb77f080ff"
2017-04-25T00:49:15.524Z HTTP+: #049:     --> 201   (4.4 ms)
2017-04-25T00:49:15.526Z WARNING: changeCache: Error unmarshaling doc "d02bb9fd-6968-4fba-b9c4-1bcfbd3a25a6": <nil> -- db.(*changeCache).DocChanged.func1() at change_cache.go:354
2017-04-25T00:49:15.526Z WARNING: changeCache: Error unmarshaling doc "cb15a198-8c66-43a2-bfa1-2ffeb336256a": <nil> -- db.(*changeCache).DocChanged.func1() at change_cache.go:354
2017-04-25T00:49:15.526Z WARNING: changeCache: Error unmarshaling doc "a48fef05-a6cd-4de1-a533-25ddad8180f6": <nil> -- db.(*changeCache).DocChanged.func1() at change_cache.go:354
2017-04-25T00:49:15.527Z WARNING: changeCache: Error unmarshaling doc "78cfd902-653f-42f9-82d9-cbd59c3fde66": <nil> -- db.(*changeCache).DocChanged.func1() at change_cache.go:354
2017-04-25T00:49:15.527Z WARNING: changeCache: Error unmarshaling doc "d9639abf-fdb7-407f-b6a9-993054c8cce3": <nil> -- db.(*changeCache).DocChanged.func1() at change_cache.go:354
2017-04-25T00:49:15.527Z WARNING: changeCache: Error unmarshaling doc "7e0c3455-d62b-4b5a-8912-b0b148eeed7a": <nil> -- db.(*changeCache).DocChanged.func1() at change_cache.go:354
2017-04-25T00:49:15.527Z WARNING: changeCache: Error unmarshaling doc "edbfae00-c52b-4708-9a16-22f9f16c3286": <nil> -- db.(*changeCache).DocChanged.func1() at change_cache.go:354
2017-04-25T00:49:15.527Z WARNING: changeCache: Error unmarshaling doc "9996fba6-caa6-40ef-9153-392922f9f7fd": <nil> -- db.(*changeCache).DocChanged.func1() at change_cache.go:354
2017-04-25T00:49:15.527Z WARNING: changeCache: Error unmarshaling doc "93e98326-2621-4524-8fac-cc2e88112390": <nil> -- db.(*changeCache).DocChanged.func1() at change_cache.go:354
2017-04-25T00:49:15.527Z WARNING: changeCache: Error unmarshaling doc "49059018-42fd-48c1-8eb3-38f6f3b26b14": <nil> -- db.(*changeCache).DocChanged.func1() at change_cache.go:354
2017-04-25T00:49:15.527Z WARNING: changeCache: Error unmarshaling doc "0fdd3277-6216-4779-a6ea-60e1ecb3bfcf": <nil> -- db.(*changeCache).DocChanged.func1() at change_cache.go:354
2017-04-25T00:49:15.527Z WARNING: changeCache: Error unmarshaling doc "caac458c-082f-48f8-aa2f-a8c900b26c27": <nil> -- db.(*changeCache).DocChanged.func1() at change_cache.go:354
2017-04-25T00:49:15.527Z WARNING: changeCache: Error unmarshaling doc "08a31758-c8a0-47f3-a010-b370cebbaffe": <nil> -- db.(*changeCache).DocChanged.func1() at change_cache.go:354
2017-04-25T00:49:15.527Z WARNING: changeCache: Error unmarshaling doc "29ea3b4b-1b4f-4a98-a2ce-769e82cda0c0": <nil> -- db.(*changeCache).DocChanged.func1() at change_cache.go:354
2017-04-25T00:49:15.527Z Changes+: Notifying that "data-bucket" changed (keys="{_sync:user:admin}") count=2
2017-04-25T00:49:15.532Z WARNING: changeCache: Error unmarshaling doc "f102b5e2-1d76-4b70-8eba-331cc632ac3b": <nil> -- db.(*changeCache).DocChanged.func1() at change_cache.go:354
2017-04-25T00:49:15.527Z Cache: Received #1 ("_user/admin")
2017-04-25T00:49:15.534Z Cache: Initialized cache for channel "*" with options: &{ChannelCacheMinLength:50 ChannelCacheMaxLength:500 ChannelCacheAge:1m0s}
2017-04-25T00:49:15.535Z Cache:     #1 ==> channel "*"
```

**Comment by sethrosetter** [comment]
This appears to be fixed with 1.4.2-357 and 5.0.0-2759
