### ISSUE TITLE
test_sg_feed_changed_with_xattrs_importEnabled fails with duplicate revs in changes feed

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/sync_gateway#2828]
### Sync Gateway version
SG 1.5.0-538.   

### Operating system
CentOS 7.

### Config file
```
{
    "out.stdout": {
        "adminInterface": "0.0.0.0:4985", 
        "cluster_config": {
            "bucket": "data-bucket", 
            "data_dir": ".", 
            "password": "password", 
            "server": "http://192.168.33.20:8091", 
            "username": "data-bucket"
        }, 
        "compressResponses": false, 
        "databases": {
            "db": {
                "bucket": "data-bucket", 
                "channel_index": {
                    "bucket": "index-bucket", 
                    "num_shards": 16, 
                    "password": "password", 
                    "server": "http://192.168.33.20:8091", 
                    "username": "index-bucket", 
                    "writer": true
                }, 
                "enable_shared_bucket_access": true, 
                "password": "password", 
                "server": "http://192.168.33.20:8091", 
                "username": "data-bucket"
            }
        }, 
        "interface": ":4984", 
        "log": [
            "CRUD+", 
            "Cache+", 
            "HTTP+", 
            "Changes+"
        ], 
        "maxCouchbaseConnections": 16, 
        "maxFileDescriptors": 90000, 
        "maxIncomingConnections": 0, 
        "slowServerCallWarningThreshold": 500
    }
}
```

### Log output
http://uberjenkins.sc.couchbase.com:8080/job/cen7-sync-gateway-functional-tests-base-di/838/testReport/testsuites.syncgateway.functional.tests/test_xattrs/test_sg_feed_changed_with_xattrs_importEnabled_sync_gateway_default_functional_tests_100_10_/

### Expected behavior
Test should pass - no duplicate revs for doc ids.

### Actual behavior
Duplicate revs for doc ids shows up in the changes feed.

### Steps to reproduce
` pytest -s -k test_sg_feed_changed_with_xattrs_importEnabled --ci --xattrs --mode=di --server-version=5.0.0-3490 --sync-gateway-version=1.5.0-538 testsuites/syncgateway/functional/tests/`

**Comment by adamcfraser** [comment]
Should be addressed by https://github.com/couchbaselabs/sync-gateway-accel/pull/178.

**Comment by raghusarangapani** [comment]
Test still failing with 1.5.0-546:

http://uberjenkins.sc.couchbase.com:8080/job/cen7-sync-gateway-functional-tests-base-di-converg/3/testReport/

**Comment by adamcfraser** [comment]
@raghusarangapani Looking at the test, it's issuing the changes request with a 10 millisecond timeout.  This seems unusual - is this intentional?

**Comment by adamcfraser** [comment]
From the Sync Gateway logs, this looks like the expected behaviour when a timeout occurs before the full set of records are returned when using accel - the subsequent request has the possibility of returning duplicate entries.

Using longpoll with such a short timeout goes contrary to the idea of longpoll (to wait for subsequent changes), and looks like it's resulting in unexpected results here.

**Comment by raghusarangapani** [comment]
I found a run where it passed with 1.5.0-540:
http://uberjenkins.sc.couchbase.com:8080/job/cen7-sync-gateway-functional-tests-base-di/855/consoleFull

Will re-run the test. Is there a recommended minimum?

**Comment by raghusarangapani** [comment]
I ran the test with increased timeout suggested by @adamcfraser with the PR https://github.com/couchbaselabs/mobile-testkit/pull/1399 , all the 4 test_sg_feed_changed_with_xattrs_importEnabled tests timed out:

http://uberjenkins.sc.couchbase.com:8080/job/cen7-sync-gateway-functional-tests-base-di-converg/14/

**Comment by adamcfraser** [comment]
@raghusarangapani It looks like there's still a test issue of some kind here.  Looking at the logs for [one of the runs](http://uberjenkins.sc.couchbase.com:8080/job/cen7-sync-gateway-functional-tests-base-di-converg/14/testReport/junit/testsuites.syncgateway.functional.tests/test_xattrs/test_sg_feed_changed_with_xattrs_importEnabled_sync_gateway_default_functional_tests_10_10_/) I can see:

```
Started adding 10 docs via SDK ...
Docs creation via SDK done
[Changes Tracker] Changes Tracker Starting ...
POST http://172.23.121.28:4984/db/_changes 200
[Changes Tracker] New changes: 1
[Changes Tracker] Total processed changes: 0
POST http://172.23.121.28:4984/db/_changes 200
[Changes Tracker] New changes: 10
[Changes Tracker] Total processed changes: 10
```

At this point the test has received all expected changes, but continues looping and executing additional changes requests (that as expected don't return any more data).

It's possible there's always been a test bug here (where it doesn't stop looping when it's received the expected changes), that was previously hidden by the 10ms timeout on each changes request.
