### ISSUE TITLE
Report parameters on N1QL errors

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3798]
Originally reported in https://forums.couchbase.com/t/5001-panic-runtime-error-index-out-of-range/18682

This log in particular:

```
2018-10-09T09:04:30.038+08:00 [WRN] Error when querying index using statement: [SELECT [op.name, LEAST(meta(`kitchen`).xattrs._sync.sequence, op.val.seq),IFMISSING(op.val.
rev,null),IFMISSING(op.val.del,null)][1] AS seq, [op.name, LEAST(meta(`kitchen`).xattrs._sync, op.val.seq),IFMISSING(op.val.rev,null),IFMISSING(op.val.del,null)][2] AS rRev, [op.name, LEAST(meta(`kitchen`).xattrs._sync, op.val.seq),IFMISSING(op.val.rev,null),IFMISSING(op.val.del,null)][3] AS rDel, meta(`kitchen`).xattrs._sync.rev AS rev, meta(`kitchen`).xattrs._sync.flags AS flags, META(`kitchen`).id AS id FROM `kitchen` UNNEST OBJECT_PAIRS(meta(`kitchen`).xattrs._sync.channels) AS op WHERE [op.name, LEAST(meta(`kitchen`).xattrs._sync.sequence, op.val.seq),IFMISSING(op.val.rev,null),IFMISSING(op.val.del,null)]  BETWEEN  [$channelName, $startSeq] AND [$channelName, $endSeq]] -- base.(*CouchbaseBucketGoCB).Query() at bucket_n1ql.go:63
2018-10-09T09:04:30.038+08:00 [INF] Query: N1QL Query("channels") took 1.017947623s
2018-10-09T09:04:30.038+08:00 [WRN] MultiChangesFeed got error reading changes feed "7a40a944": [5001] Panic: runtime error: index out of range -- db.(*Database).SimpleMul
tiChangesFeed.func1() at changes.go:490
2018-10-09T09:04:30.038+08:00 [INF] Changes: MultiChangesFeed done   (to 7a40a944)
```

indicates that Sync Gateway is calling n1ql with invalid startSeq and endSeq.

There should be a logging setting to log those values, and additional validation to make sure invalid values aren't passed.

**Comment by wilsondy** [comment]
Having a similar issue with 2.1.1 against 5.5.1.  We aren't getting data down on the channel mentioned.  Is there a known workaround?

```
2018-10-29T13:31:34.656Z [WRN] MultiChangesFeed got error reading changes feed "content": [5001] Panic: runtime error: index out of range -- db.(*Database).SimpleMultiChangesFeed.func1() at changes.go:493
2018-10-29T13:31:43.677Z [WRN] Error when querying index using statement: [SELECT [op.name, LEAST(meta(`sync_gateway`).xattrs._sync.sequence, op.val.seq),IFMISSING(op.val.rev,null),IFMISSING(op.val.del,null)][1] AS seq, [op.name, LEAST(meta(`sync_gateway`).xattrs._sync, op.val.seq),IFMISSING(op.val.rev,null),IFMISSING(op.val.del,null)][2] AS rRev, [op.name, LEAST(meta(`sync_gateway`).xattrs._sync, op.val.seq),IFMISSING(op.val.rev,null),IFMISSING(op.val.del,null)][3] AS rDel, meta(`sync_gateway`).xattrs._sync.rev AS rev, meta(`sync_gateway`).xattrs._sync.flags AS flags, META(`sync_gateway`).id AS id FROM `sync_gateway` UNNEST OBJECT_PAIRS(meta(`sync_gateway`).xattrs._sync.channels) AS op WHERE [op.name, LEAST(meta(`sync_gateway`).xattrs._sync.sequence, op.val.seq),IFMISSING(op.val.rev,null),IFMISSING(op.val.del,null)]  BETWEEN  [$channelName, $startSeq] AND [$channelName, $endSeq]] -- base.(*CouchbaseBucketGoCB).Query() at bucket_n1ql.go:63
```

**Comment by adamcfraser** [comment]
@wilsondy Can you provide any more specifics on the state of the 'content' channel when that query would have been executed, so that we can dig into the underlying root cause?

**Comment by JFlath** [comment]
Hi All,

Quickly stepping in here to try and head off any confusion.

@wilsondy - As we have another channel of communication open, let's use that to follow up in more detail for now.
@adamcfraser - I'll make sure any relevant information gets relayed back to you and your team.

Thanks,

James

**Comment by adamcfraser** [comment]
The underlying issue here looks like a potential query service issue (i.e. the 'index out of range' error is actually a go slice error being emitted by the query service).  Getting parameters included in error log output is a good idea in any case, though.

**Comment by tleyden** [comment]
The underlying issue was fixed in https://issues.couchbase.com/browse/MB-32120

**Comment by erpankaj22** [comment]
I am using CBS 6.0 but the issue still persist where I see similar errors on sync gateway. So I have went back to using views.

**Comment by chinhnguyen** [comment]
The problem seems to still be in 6.0.0, Below is the log from my Sync Gateway, there are 2 channels to sync and this error happens on 1 of them:

```
2020-07-25T07:43:52.654Z [INF] Changes: MultiChangesFeed(channels: {ol_ord_new_20042416263859}, options: {Since:7261453 Limit:0 Conflicts:false IncludeDocs:false Wait:true Continuous:true Terminator:0xc425b5cde0 HeartbeatMs:0 TimeoutMs:0 ActiveOnly:false}) ...   (to apps)
2020-07-25T07:43:54.695Z [INF] SyncMsg: [63240467] #2: Type:subChanges Since:0 Filter:sync_gateway/bychannel Channels:20042416263859,etc_20042416263859  User:apps
2020-07-25T07:43:54.695Z [INF] Changes: MultiChangesFeed(channels: {20042416263859, etc_20042416263859}, options: {Since:0 Limit:0 Conflicts:false IncludeDocs:false Wait:false Continuous:false Terminator:0xc42485b620 HeartbeatMs:0 TimeoutMs:0 ActiveOnly:false}) ...   (to apps)
2020-07-25T07:43:54.695Z [INF] Cache: getCachedChanges("20042416263859", 23:0) --> 1 changes valid from #7276574
2020-07-25T07:43:54.695Z [INF] Cache:   Querying 'channels' view for "20042416263859" (start=#1, end=#7276574, limit=0)
2020-07-25T07:43:54.775Z [WRN] MultiChangesFeed got error reading changes feed "20042416263859": [5001] Panic: runtime error: index out of range -- db.(*Database).SimpleMultiChangesFeed.func1() at changes.go:490
2020-07-25T07:43:55.823Z [INF] SyncMsg: [366b74ba] #2: Type:subChanges Since:7261453 Continuous:true Filter:sync_gateway/bychannel Channels:ol_ord_new_20042416263859  User:apps
2020-07-25T07:43:55.823Z [INF] Changes: MultiChangesFeed(channels: {ol_ord_new_2
```

**Comment by bbrks** [comment]
@chinhnguyen this issue was fixed in 6.0.1 and 6.5.0

**Comment by chinhnguyen** [comment]
Thanks @bbrks. Upgrading to 6.5 did fix the issue.
