### ISSUE TITLE
Error in sync function example: use of throw

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#995]
https://forums.couchbase.com/t/documentation-snafu-on-sync-function/4573/1

This should get fixed asap - I recall another user was using throw without the braces, and now I know where they got the idea.

**Comment by adamcfraser** [comment]
Fixed with https://github.com/couchbaselabs/couchbase-mobile-portal/commit/20b92917f68d6f90e7d053fb8407945c9feeb717

**Comment by andreibaranouski** [comment]
Hi @JeffThomasWriter  
I still don't see the changes in http://developer.couchbase.com/mobile/develop/guides/sync-gateway/sync-function-api-guide/validation/index.html#example

Do I need any additional steps to apply the changes?

**Comment by adamcfraser** [comment]
The latest version from https://github.com/couchbaselabs/couchbase-mobile-portal hasn't been pushed to the site yet.  It's expected to be included in the forthcoming update to the site.
